
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: stu_web
    registry:
      address: zookeeper://192.168.56.188:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3