dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://192.168.56.188:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///email
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

