
spring:
  mail:
    protocol: smtp
    host: smtp.163.com
    username: f845835812@163.com
    password: fanglijun1314
dubbo:
  application:
    name: mail_service
  registry:
    address: zookeeper://192.168.56.188:2181
  protocol:
    port: -1
  consumer:
    check: false


